### ISSUE TITLE
My Internet is working,Translation failed, retrying...

### ISSUE THREAD

**Issue by lilianglailai** [hymhub/language-translate#15]
D:\cs_dev\translate\node_modules\got\source\request-as-event-emitter.js:178
                                        error = new RequestError(error, options);
                                                ^

GotError [RequestError]: tunneling socket could not be established, cause=socket hang up
    at ClientRequest.<anonymous> (D:\cs_dev\translate\node_modules\got\source\request-as-event-emitter.js:178:14)
    at Object.onceWrapper (node:events:632:26)
    at ClientRequest.emit (node:events:529:35)
    at origin.emit (D:\cs_dev\translate\node_modules\@szmarczak\http-timer\source\index.js:37:11)
    at ClientRequest.onError (D:\cs_dev\translate\node_modules\tunnel\lib\tunnel.js:183:21)
    at Object.onceWrapper (node:events:632:26)
    at ClientRequest.emit (node:events:517:28)
    at Socket.socketOnEnd (node:_http_client:525:9)
    at Socket.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ECONNRESET',
  host: 'translate.google.com',
  hostname: 'translate.google.com',
  method: 'GET',
  path: '/',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://translate.google.com/',
  gotOptions: {
    path: '/',
    protocol: 'https:',
    slashes: true,
    auth: null,
    host: 'translate.google.com',
    port: null,
    hostname: 'translate.google.com',
    hash: null,
    search: null,
    query: null,
    pathname: '/',
    href: 'https://translate.google.com/',
    retry: {
      retries: [Function (anonymous)],
      methods: Set(6) { 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' },
      statusCodes: Set(7) { 408, 413, 429, 500, 502, 503, 504 },
      errorCodes: Set(8) {
        'ETIMEDOUT',
        'ECONNRESET',
        'EADDRINUSE',
        'ECONNREFUSED',
        'EPIPE',
        'ENOTFOUND',
        'ENETUNREACH',
        'EAI_AGAIN'
      }
    },
    headers: {
      'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
      'accept-encoding': 'gzip, deflate'
    },
    hooks: {
      beforeRequest: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: [],
      beforeError: [],
      init: []
    },
    decompress: true,
    throwHttpErrors: true,
    followRedirect: true,
    stream: false,
    form: false,
    json: false,
    cache: false,
    useElectronNet: false,
    agent: TunnelingAgent {
      options: {
        proxy: {
          host: '127.0.0.1',
          port: 8080,
          headers: { 'User-Agent': 'Node' }
        }
      },
      proxyOptions: {
        host: '127.0.0.1',
        port: 8080,
        headers: { 'User-Agent': 'Node' }
      maxSockets: Infinity,
      requests: [],
      sockets: [],
      _events: [Object: null prototype] { free: [Function: onFree] },
      _eventsCount: 1,
      request: [Function: request],
      createSocket: [Function: createSecureSocket],
      defaultPort: 443
    },
    method: 'GET',
    forceRefresh: true
  }
}

**Comment by lilianglailai** [comment]
solve

**Comment by lilianglailai** [comment]
> D:\cs_dev\translate\node_modules\got\source\request-as-event-emitter.js:178 error = new RequestError(error, options); ^
> 
> GotError [RequestError]: tunneling socket could not be established, cause=socket hang up at ClientRequest. (D:\cs_dev\translate\node_modules\got\source\request-as-event-emitter.js:178:14) at Object.onceWrapper (node:events:632:26) at ClientRequest.emit (node:events:529:35) at origin.emit (D:\cs_dev\translate\node_modules@szmarczak\http-timer\source\index.js:37:11) at ClientRequest.onError (D:\cs_dev\translate\node_modules\tunnel\lib\tunnel.js:183:21) at Object.onceWrapper (node:events:632:26) at ClientRequest.emit (node:events:517:28) at Socket.socketOnEnd (node:_http_client:525:9) at Socket.emit (node:events:529:35) at endReadableNT (node:internal/streams/readable:1400:12) at process.processTicksAndRejections (node:internal/process/task_queues:82:21) { code: 'ECONNRESET', host: 'translate.google.com', hostname: 'translate.google.com', method: 'GET', path: '/', socketPath: undefined, protocol: 'https:', url: 'https://translate.google.com/', gotOptions: { path: '/', protocol: 'https:', slashes: true, auth: null, host: 'translate.google.com', port: null, hostname: 'translate.google.com', hash: null, search: null, query: null, pathname: '/', href: 'https://translate.google.com/', retry: { retries: [Function (anonymous)], methods: Set(6) { 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' }, statusCodes: Set(7) { 408, 413, 429, 500, 502, 503, 504 }, errorCodes: Set(8) { 'ETIMEDOUT', 'ECONNRESET', 'EADDRINUSE', 'ECONNREFUSED', 'EPIPE', 'ENOTFOUND', 'ENETUNREACH', 'EAI_AGAIN' } }, headers: { 'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)', 'accept-encoding': 'gzip, deflate' }, hooks: { beforeRequest: [], beforeRedirect: [], beforeRetry: [], afterResponse: [], beforeError: [], init: [] }, decompress: true, throwHttpErrors: true, followRedirect: true, stream: false, form: false, json: false, cache: false, useElectronNet: false, agent: TunnelingAgent { options: { proxy: { host: '127.0.0.1', port: 8080, headers: { 'User-Agent': 'Node' } } }, proxyOptions: { host: '127.0.0.1', port: 8080, headers: { 'User-Agent': 'Node' } maxSockets: Infinity, requests: [], sockets: [], _events: [Object: null prototype] { free: [Function: onFree] }, _eventsCount: 1, request: [Function: request], createSocket: [Function: createSecureSocket], defaultPort: 443 }, method: 'GET', forceRefresh: true } }

**Comment by lilianglailai** [comment]
solve
